# Generated by Django 5.0.1 on 2024-01-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('industry_category', models.CharField(choices=[('Transport', 'Transport'), ('Banking', 'Banking'), ('Agriculture', 'Agriculture')], max_length=50)),
                ('total_vehicles', models.PositiveIntegerField()),
                ('fossil_fuel_cars', models.PositiveIntegerField()),
                ('electric_vehicles', models.PositiveIntegerField()),
                ('source_of_energy_1', models.CharField(choices=[('Hydro', 'Hydro'), ('Solar', 'Solar')], max_length=50)),
                ('energy_consumption_1', models.FloatField()),
                ('source_of_energy_2', models.CharField(choices=[('Hydro', 'Hydro'), ('Solar', 'Solar')], max_length=50)),
                ('energy_consumption_2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.PositiveIntegerField()),
                ('female_employees', models.PositiveIntegerField()),
                ('male_employees', models.PositiveIntegerField()),
                ('employees_with_disabilities', models.PositiveIntegerField()),
                ('employees_age_20_30', models.PositiveIntegerField()),
                ('employees_age_31_40', models.PositiveIntegerField()),
                ('employees_age_41_50', models.PositiveIntegerField()),
                ('employees_age_51_60', models.PositiveIntegerField()),
                ('employees_age_61_plus', models.PositiveIntegerField()),
            ],
        ),
    ]
